development: &default
  es_bin: '/usr/local/Cellar/elasticsearch/6.4.2/bin/elasticsearch'
  host: 'http://localhost:9200'
  port: '9200'
test:
  es_bin: '/usr/local/Cellar/elasticsearch/6.4.2/bin/elasticsearch'
  host: 'http://localhost:9250'
  port: '9250'
staging:
  <<: *default
production:
  es_bin: ''
  host: 'http://localhost:9400'
  port: '9400'
